#!/usr/bin/bash
[ -z "$1" ] && nitrogen --random --set-zoom-fill --save 2>/dev/null
SCRIPT_DIR="$(dirname $(readlink -f ${BASH_SOURCE}))"
cd $SCRIPT_DIR
CURRENT_PAPER="$(grep "file" $HOME/.config/nitrogen/bg-saved.cfg | sed 's/file=//')"
COLOR_BIN="$SCRIPT_DIR/kmeans.py"
COLOR_FILE="$HOME/.config/kitty/color.conf"
XRESC_FILE="$SCRIPT_DIR/Xresources"


$COLOR_BIN "$CURRENT_PAPER" $* > "$COLOR_FILE"
cat $COLOR_FILE | grep color | awk '{print "*" $1 ": " $2}' > $XRESC_FILE
    
printf "foreground\t$(cat $COLOR_FILE | grep color15 | cut -d' ' -f 2)\n" | tee -a $COLOR_FILE | awk '{print "*" $1 ": " $2}' >> $XRESC_FILE
printf "background\t$(cat $COLOR_FILE | grep color0 | cut -d' ' -f 2)\n" | tee -a $COLOR_FILE | awk '{print "*" $1 ": " $2}' >> $XRESC_FILE
printf "cursor_text_color\t$(cat $COLOR_FILE | grep color13 | cut -d' ' -f 2)\n" >> $COLOR_FILE
# | tee -a $COLOR_FILE | awk '{print "*" $1 ": " $2}' >> $XRESC_FILE

kitty @ --to=unix:/tmp/.kitty set-colors --all --configured "$COLOR_FILE"
# xrdb -merge $XRESC_FILE
# rm input.png output.png
